### ISSUE TITLE
Cannot deploy Azure nodejs function after update to v1.15.1

### ISSUE THREAD

**Issue by olafurfannsker** [microsoft/vscode-azurefunctions#4197]
After updating VSCode extension to V 1.15.1, deploying to an existing function using the extension fails with an error message: "Internal error: Expected value to be neither null nor undefined: newSiteName".    (newSiteName is nowhere to be found in the project).  After downgrading I get the same message so it's a puzzle because it was working before.   I'm using VSCode on a MAC with Sonoma.

Publishing through the command line works like a charm.

I tried even to create a new example project and got the same issue.

regards,
Olafur

**Comment by nturinski** [comment]
Hi there, sorry that you're running into problems.

Could you tell me exactly what steps you are doing to deploy? Like, the entry point, what you click after that, etc.

Also, could you try downgrading to v1.14.3 to see if that fixes the error?

**Comment by RafaelFN1230** [comment]
Hello running to the same issue.
Aplication runs fine in local enviroment, but when I go to deploy to azure I get:

"Internal error: Expected value to be neither null nor undefined: newSiteName"

**Comment by monkeyibrowstudios** [comment]
me too.... the deployment process was working fine a few months ago and nothing changed since

**Comment by nturinski** [comment]
Could you please try running this alpha version of the extension? I think that it may resolve your issue.

1. Unzip the zip file
2. In VS Code, press F1 > Install from VSIX
3. Click the .vsix file that was extracted from the zip file
4. Reload VS Code

Please let me know if this resolves the deployment issue!

[vscode-azurefunctions-1.15.2-alpha.0.zip](https://github.com/user-attachments/files/16534315/vscode-azurefunctions-1.15.2-alpha.0.zip)

**Comment by monkeyibrowstudios** [comment]
unfortunatelly, the same error still persists. (installed the alpha version and restarted VS Code)

**Comment by nturinski** [comment]
Could  you provide some details about your function app? Like runtime, OS, and what app service plan you are using?

If you're able, can you try making a new app and deploying to that?

**Comment by nturinski** [comment]
Could anyone having this issue answer how they are deploying their app?

There are a few entry points to start a function deployment:
1. Right-click a function app node in the tree view, click `Deploy to Function App...`
2. Click the function button on the Workspace ribbon and click `Deploy to Azure...`
3. Right-click the `Local Project` node and click `Deploy to Azure...`
4. The command palette

**Comment by RobertoArmas** [comment]
Hi I'm facing the same issue after upgrade. Do you know if that will be fixed soon? Do I need to downgrade the version?

**Comment by RobertoArmas** [comment]
I installed alpha version of the extension. It solve the issue.
